version: "3.8"

services:

  springboot:
    build: ./backend/springboot
    container_name: springboot_app
    expose:
      - "8080"

  fastapi:
    build: ./backend/fastapi
    container_name: fastapi_app
    expose:
      - "8000"

  frontend:
    build: ./frontend
    container_name: react_app
    expose:
      - "80"

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - springboot
      - fastapi
      - frontend